In [4]:
import tensorflow as tf
print(tf.__version__)

2.20.0


Creates a Tensor

In [14]:
scalar = tf.constant(7)
vector = tf.constant([10,10])
matrix = tf.constant([[10,7],[7,10]])
#dimension 
print(scalar.ndim)
print(vector.ndim)
print(matrix.ndim)

0
1
2


In [15]:
#tf.constant(//values,//dtype,//shape,//name)
#Used to create a tensor which values cant be changed

In [24]:
changeable = tf.Variable([10,7])
unchangeable = tf.constant([10,7])

In [25]:
# unchangeable[0] = 5 TypeError: 'ResourceVariable' object does not support item assignment
changeable[0].assign(11)
changeable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11,  7])>

In [26]:
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility 
random_1 = random_1.uniform(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [27]:
#Shuffle the Order of the element in the tensor 
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])

In [33]:
tf.random.shuffle(not_shuffled,seed=42)
#Randomizes the data so the network doesn't memorize the order

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

In [34]:
#Creating Tensors from Numpy

In [35]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [36]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into Tensor

The main differences bw Numpy arrays and Tf tensor is that tensors can be run on a GPU

In [49]:
import numpy as np 

In [50]:
arr = np.arange(1,25,dtype=np.int32)
arr
# np.arange(start,end(exclude),dtype)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [51]:
ten1 = tf.constant(arr,)
ten2 = tf.constant(arr,shape = (2,3,4))
print(ten1)
print(ten2)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)


oldshape = n and newshape = (a,b,c,...)
<br> a x b x c x... = n

### Get Info from tensor 

There will be times when you'll want to get different pieces of information from your tensors, in particuluar, you should know the following tensor vocabulary:

Shape: The length (number of elements) of each of the dimensions of a tensor.
Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
Axis or Dimension: A particular dimension of a tensor.
Size: The total number of items in the tensor.

In [54]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5))

In [55]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [58]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)