In [2]:
import tensorflow as tf
print(tf.__version__)

C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


2.20.0


Creates a Tensor

In [3]:
scalar = tf.constant(7)
vector = tf.constant([10,10])
matrix = tf.constant([[10,7],[7,10]])
#dimension 
print(scalar.ndim)
print(vector.ndim)
print(matrix.ndim)

0
1
2


In [4]:
#tf.constant(//values,//dtype,//shape,//name)
#Used to create a tensor which values cant be changed

In [5]:
changeable = tf.Variable([10,7])
unchangeable = tf.constant([10,7])

In [6]:
# unchangeable[0] = 5 TypeError: 'ResourceVariable' object does not support item assignment
changeable[0].assign(11)
changeable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11,  7])>

In [7]:
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility 
random_1 = random_1.uniform(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [8]:
#Shuffle the Order of the element in the tensor 
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])

In [9]:
tf.random.shuffle(not_shuffled,seed=42)
#Randomizes the data so the network doesn't memorize the order

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

In [10]:
#Creating Tensors from Numpy

In [11]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [12]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into Tensor

The main differences bw Numpy arrays and Tf tensor is that tensors can be run on a GPU

In [13]:
import numpy as np 

In [14]:
arr = np.arange(1,25,dtype=np.int32)
arr
# np.arange(start,end(exclude),dtype)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [15]:
ten1 = tf.constant(arr,)
ten2 = tf.constant(arr,shape = (2,3,4))
print(ten1)
print(ten2)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)


oldshape = n and newshape = (a,b,c,...)
<br> a x b x c x... = n

### Get Info from tensor 

There will be times when you'll want to get different pieces of information from your tensors, in particuluar, you should know the following tensor vocabulary:

Shape: The length (number of elements) of each of the dimensions of a tensor.
Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
Axis or Dimension: A particular dimension of a tensor.
Size: The total number of items in the tensor.

In [16]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5))

In [17]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [18]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

Indexing

In [19]:
#Just like python list 

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [20]:
rank_2_tensor = tf.constant([[1,2],[3,4]])

In [21]:
rank_2_tensor.ndim

2

In [22]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4])>

In [23]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]

In [24]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]])>

In [25]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) # "-1" means expends the final axis 

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]])>

In [26]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

### tensor Operations

In [31]:
#Manipulating Tensors
tensor = tf.constant([[10,20],[40,90]])
tensor + 100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110, 120],
       [140, 190]])>

In [58]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 200],
       [400, 900]])>

In [59]:
tf.math.add(tensor,100)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110, 120],
       [140, 190]])>

In [60]:
tf.math.multiply(tensor,100)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1000, 2000],
       [4000, 9000]])>

In [61]:
print(rank_2_tensor)
print(rank_2_tensor * rank_2_tensor)
tf.math.multiply(rank_2_tensor,[[1,2],[3,4]])

#line 2 and 3 give same result 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]])>

In [62]:
tf.matmul(rank_2_tensor,[[1,2],[3,4]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]])>

tf.matmul ---> Dot product 
tf.math.multiply ---> Element wise 

In [66]:
#Short hand code for matrix multiplication 
X = tf.constant([[1,2,3],[4,5,6],[7,8,9]]) #shape ===> 3x3 (MxK)
y = tf.constant([[1,2],[4,5],[3,6]]) #shape ===> 3x2 (KxN)
Z = X@y #shape ===> 3x2 (MxN)
Z

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 18,  30],
       [ 42,  69],
       [ 66, 108]])>

In [65]:
Z.shape, Z.ndim

(TensorShape([3, 2]), 2)

In [67]:
A = tf.constant([[1, 2],
                 [3, 4]])

B = tf.constant([[5, 6],
                 [7, 8]])

result = tf.tensordot(A, B, axes=1)

print(result)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [ ]:
B2 = tf.constant([[2,3],[3,4],[5,6]])
tf.reshape(B2,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 3],
       [4, 5, 6]])>

In [71]:
B2.dtype

tf.int32

In [73]:
tf.cast(B2,dtype=float)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2., 3.],
       [3., 4.],
       [5., 6.]], dtype=float32)>